"use client";

import { Comic_Neue, Work_Sans, Orbitron } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
// import { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'Zuzuplay App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient();

const comicNeue = Comic_Neue({
  weight: ["300", "400", "700"], // Specify the weights you need
  subsets: ["latin"],
});

const workSans = Work_Sans({
  weight: ["300", "400", "700"], // Specify the weights you need
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const orbitron = Orbitron({
  weight: ["400", "700"], // Specify the weights you need
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); //location.pathname;
  const isGame = pathname.includes("game");
  // const [isGame, setIsGame] = useState(false);
  // useEffect(() => {
  //   setIsGame(pathname.includes("game"));
  // }, [pathname]);
  // const router = useRouter()

  // useEffect(() => {
  //   // Function to check if the user is on a mobile device
  //   const isMobile = () => {
  //     const userAgent = navigator.userAgent || navigator.vendor || window.opera
  //     return /android|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(
  //       userAgent
  //     )
  //   }

  //   // Redirect to "not supported" page if not on a mobile device
  //   if (!isMobile()) {
  //     router.replace('/not-supported')
  //   }
  // }, [router])

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en" className="h-full bg-white text-black">
        <body className={`${comicNeue.className} ${orbitron.variable} h-full`}>
          <div className="min-h-screen bg-white">
            <div className="min-h-screen flex flex-col">
              <div className={isGame == false ? "flex-grow px-5 pt-5 lg:px-0 lg:pt-0" : ""}>
                {children}
              </div>
              <ToastContainer />
            </div>
          </div>
        </body>
      </html>
    </QueryClientProvider>
  );
}
